import Head from "next/head";
import Sidebar from "../components/Sidebar";
import styled from "styled-components";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <MainPage>
        <MainPageContainer>
          <Logo src="https://facebookbrand.com/wp-content/uploads/2020/10/Logo_Messenger_NewBlurple-399x399-1.png?w=399&h=399" />
          <Text>CHATAPP BY MIROSLAW</Text>
        </MainPageContainer>
      </MainPage>
    </Container>
  );
}

const Container = styled.div`
  display: flex;
`;

const Text = styled.span`
  text-align: center;
  font-size: 20px;
  font-weight: 600;
  background: -webkit-linear-gradient(
    45deg,
    #ff9494,
    #b257e6,
    #e657e6,
    #ff9494,
    #e657e6
  );
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
`;

const MainPage = styled.div`
  background-color: rgb(250, 250, 250);
  display: grid;
  place-items: center;
  height: 100vh;
  flex: 1;
  border-left: 1px solid lightgray;
`;
const MainPageContainer = styled.div`
  padding: 100px;
  display: flex;
  flex-direction: column;
  align-items: right;
`;

const Logo = styled.img`
  height: 300px;
  width: 300px;
  margin-bottom: 50px;
`;
